# Categories involved in the problem:
# it must be always a cell array, also with a single element
# e.g. setlist.categories = {'mug'}
# --> look in the 'iCW' folder to check the available categories
# (in this case: 'mug', 'remote', and 'sodabottle')
CATEGORIES: ["mug", "sodabottle"]

# Experiment kind:
# either 'cat' (obj. categorization) or 'id' (obj. identification)
EXP_KIND: "id"

# At each level of the 'iCW' hierarchy, we must define
# one train, one validation and one test set:
# e.g. in this task we want to learn to discriminate
# between 10 objects (5 mugs and 5 remotes)
# by training on 4 transformation sequences per object
# and testing the system on the mixed sequence

# Objects per category:
# if the experiment is identification, the three sets will be equal
# (like in this example)
# in categorization, instead, usually the system is trained
# on some object instances per category and tested on others
# (and usually one or two instances are kept for validation)
# --> look in the 'iCW' folder to check
# the number of objects per category available (in this case: 10)
OBJ_PER_CAT:
  TRAIN: ["1"]
  VAL: ["1"]
  TEST: ["1"]

# Transformations per object:
# --> look in the 'iCW' folder to check
# the transformations per object available
TRANSF_PER_OBJ:
  TRAIN: ["ROT2D", "ROT3D", "SCALE", "TRANSL"] 
  VAL: ["ROT2D", "ROT3D", "SCALE", "TRANSL"]
  TEST: ["MIX"]

# Days per transformation:
# there are two sequences, acquired in different days, available
# you can choose to train on the first one ["1"], or the second one ["2"]
# or both ["1", "2"] (the same for testing)
# here we chose day 1
DAY_PER_TRANSF:
  TRAIN: ["1"]
  VAL: ["1"]
  TEST: ["2"]

# Whether to put a max limit on the #frames
# to be sampled (randomly) from each sequence
LIMIT_FRAMES:
  TRAIN:
    ACTIVE: True
    MAX: 50
  VAL:
    ACTIVE: True
    MAX: 50
  # differently from training and validation,
  # the test frames are extracted as contiguous sequences
  # (like a short video on which you test the system):
  # you can start the sequence
  # either from a random or arbitrary frame:
  # in the first case, STARTING_IMG: -1
  # in the second case, STARTING_IMG: <number>
  # such that STARTING_IMG + MAX < ~70
  TEST:
    ACTIVE: True
    MAX: 50
    STARTING_IMG: 1

# Whether to use a fraction of the training set for validation:
# this flag must be set to true in case you defined equal
# training and validation sets (like in this example,
# --> pay attention to disable the flag when you specify
# training and validation sets as different sets
DIVIDE_TRAINVAL_SET:
  ACTIVE: True
  # depending on whether we want to sample
  # validation frames at constant step or randomly
  # this field can be either "random" or "step"
  VALIDATION_SPLIT: "random"
  # the validation fraction will be in (0,1)
  # NOTE: if validation_split is "step" then
  # the sampling step is computed as 1/VALIDATION_PERC
  VALIDATION_PERC: 0.2
